apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: producer
  ports:
    - port: {{ .Values.producer.port }}
      targetPort: {{ .Values.producer.port }}
  type: ClusterIP