apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: smtp-secrets
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    keyvaultName: {{ .Values.keyVault.name }}
    tenantId: {{ .Values.keyVault.tenantId }}
    objects: |
      array:
        - |
          objectName: smtp-host
          objectType: secret
        - |
          objectName: smtp-port
          objectType: secret
        - |
          objectName: smtp-username
          objectType: secret
        - |
          objectName: smtp-password
          objectType: secret
  secretObjects:
    - secretName: smtp-credentials
      type: Opaque
      data:
        - objectName: smtp-host
          key: SMTP_HOST
        - objectName: smtp-port
          key: SMTP_PORT
        - objectName: smtp-username
          key: SMTP_USERNAME
        - objectName: smtp-password
          key: SMTP_PASSWORD