apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-apps
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.keyVault.workloadIdentityClientId }}