apiVersion: apps/v1
kind: Depolyment
metadata:
  name: test-deploy
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginx
