apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exam-app
  name: exam-app
  namespace: exam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exam-app
  template:



    metadata:
      labels:
        app: exam-app
    spec:
      serviceAccountName: my-sa
      containers:
      - image: nginx:1.21
        name: nginx
        envFrom:
          - configMapRef:
              name: my-cm
        volumeMounts:
          - name: vol-secret
            mountPath: /etc/secret
      volumes:
        - name: vol-secret
          secret:
            secretName: my-secret

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv 
spec:
  capacity:
    storage: 2Gi
  accessModes:          
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  hostPath:
    path: /mnt/exam
