apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain
  # Retain: بعد از delete PVC، PV نگه داشته میشه
  # Delete: بعد از delete PVC، PV هم حذف میشه
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""    # خالی = bind به PV بدون storageClass

---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
  - image: nginx
    name: pvc-pod
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-pvc