apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amirhosssein0/kafka-and-security-lab.git
    targetRevision: master
    path: helm/notification-system
  destination:
    server: https://kubernetes.default.svc
    namespace: notifications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true