apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-schedule
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amirhosssein0/kafka-and-security-lab.git
    targetRevision: master
    path: velero
    directory:
      recurse: false
      include: "backup-schedule.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true