apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-run-as-non-root
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-runAsNonRoot
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
                - falco
                - velero
                - argocd
      validate:
        message: "Pods must set securityContext.runAsNonRoot to true"
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true