apiVersion: argoproj.io/v1alpha1
kind: Application  #repo<-->cluster
metadata:
  name: kube-random-number
  namespace: argocd
spec:
  project: default 
  source:
    repoURL: https://github.com/aaghamohammadi/kube_random_number
    targetRevision: HEAD #when argocd should trigger? last commit on branch main
    path: .
  destination: #connect to which cluster??
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true #delete from cluster if delete in repo
      selfHeal: true # if change smt manually in cluster, argocd doest change anything and doesnt sync with repo
    syncOptions:
      - CreateNamespace=true