namespace: notifications

acrLoginServer: acrkafkalabdevamirhosssein0.azurecr.io

producer:
  image:
    repository: producer
    tag: v1
  replicas: 2
  port: 8080
  autoscaling:
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilization: 70

consumer:
  image:
    repository: consumer
    tag: v1
  replicas: 1

dlqHandler:
  image:
    repository: dlq-handler
    tag: v1
  replicas: 1

keyVault:
  name: kv-kafka-lab-dev
  tenantId: "62c02e1b-f29d-4dda-b8a4-9c8a7b734d78"

kafka:
  brokers: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  topic: notifications
  dlqTopic: notifications-dlq