apiVersion: v1        #our kubernetes version

kind: Pod

metadata:
  name: hello-kube      #pod's name
  labels:
    app: hello_kube

spec:         #describe the contents in our pod
  containers:
  - name: web
    image: aaghamohammadi/hello_kube:1.0.0

